version: '3'
services:
        python3:
                build: .
                container_name: 'ds-template'
                working_dir: '/app'
                environment:
                        - DISPLAY=$DISPLAY
                        - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
                volumes:
                        - ./:/app
                        - /tmp/.X11-unix:/tmp/.X11-unix
                command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --notebook-dir=/app
                ports:
                        - 8888:8888
                deploy:
                        resources:
                                reservations:
                                        devices:
                                            - capabilities: [gpu]
